### ISSUE TITLE
auth check done after upload

### ISSUE THREAD

**Issue by olsonanl** [MG-RAST/Shock#179]
Trying an upload of a large file and got this:

olson@maple:/scratch/DataForKmers/Data.2014-05-03$ time curl -X POST --data-binary @kmer.table.mem_map  http://kbase.us/services/shock-api/node
{"status":401,"data":null,"error":["No Authorization"]}
real	9m27.975s
user	0m18.317s
sys	1m5.413s

Seems like that check should be done before committing to the large upload.

**Comment by teharrison** [comment]
Fixed or unable to duplicate.  The code for both data and multipart form POST checks auth before streaming the data.  Testing this against the lastest code using curl throws me the the auth error immediately when POSTing a gigabyte size file.
