### ISSUE TITLE
[Feature request] Expose metadata / acl / file versions

### ISSUE THREAD

**Issue by MrCreosote** [MG-RAST/Shock#209]
Per Jared, individual version information for the metadata, file, and acls are stored but not accessible via the API:

```
            "version_parts" : {
                "attributes_ver" : "37a6259cc0c1dae299a7866489dff0bd",
                "acl_ver" : "6d944fe19b5ac11f16d9ab9d39ab5c11",
                "file_ver" : "ced507f0e5833a048e07dbb5c18c0813"
            },
```
Make these visible so that a user can determine what portion of the node changed. The current exposed version field is, IIUC, a version for the node as a whole.

**Comment by teharrison** [comment]
This is added with version 0.9.13.
