### ISSUE TITLE
Read-only file system

### ISSUE THREAD

**Issue by wgerlach** [MG-RAST/Shock#259]
Return error message when user tries to create a node on a Shock server whose files system went into read-only mode. Currently connection just times out.

**Comment by sebhtml** [comment]
To reproduce, first run **mount -o remount,ro /shock-mountpoint**. Then, post new content to the object storage service with the following command.

curl -X POST -H "Authorization: OAuth <SANITIZED>" http://seb-shock.mcs.anl.gov:7445/node

**Comment by teharrison** [comment]
This has been resolved.  I get this response when POSTing to a read-only filesystem when using latest version:

{"status":400,"data":null,"error":["Error parsing form: open /Volumes/data/temp/55770067919477794108674665223082153551: read-only file system"]}
