### ISSUE TITLE
Need to modify mongo timeouts.

### ISSUE THREAD

**Issue by jaredbischof** [MG-RAST/Shock#274]
Shock should try connecting to mongo several times (with 10 second timeout) at startup time.  If it continues to fail, Shock should exit with error.  If it is successful, Shock should start a new new mongo connection with a longer timeout (~5 minutes).  This is necessary because the mgo library does not distinguish between a dial timeout and a rw timeout.

**Comment by teharrison** [comment]
This is added with version 0.9.13.
