### ISSUE TITLE
Shock asks re upgrading nodes/acls even if DB is empty

### ISSUE THREAD

**Issue by MrCreosote** [MG-RAST/Shock#291]
As of 0.9.6, on startup, Shock always asks if you want to upgrade the nodes and acls to version 2, even if the database is empty. Naively, if the DB is empty Shock should just start with the most recent versions selected.

**Comment by teharrison** [comment]
I agree that is annoying when starting a new shock, as the user needs to have command line feedback on the startup.

I will add that fix to our todo list.

**Comment by teharrison** [comment]
This is fixed with version 0.9.13.
