### ISSUE TITLE
Docker build instructions

### ISSUE THREAD

**Issue by MrCreosote** [MG-RAST/Shock#297]
At least for me, the docker build command in README.md didn't work:

```
sudo docker build -t shock:latest docker/Dockerfile 
unable to prepare context: context must be a directory: /home/[bla]/localgit/Shock/docker/Dockerfile
```

This does though:
```
sudo docker build -t shock:latest docker
```

```
docker -v
Docker version 1.9.1, build a34a1d5
```

**Comment by wgerlach** [comment]
I updated the README.md, thx.

**Comment by MrCreosote** [comment]
Thanks for the fix. When I tried to build 0.9.13, it looks like docker just used a cache (I'm a docker noob) and I wound up with the 0.9.12 binary. Adding --no-cache to the build command fixed that - noting that in the build instructions (assuming that's the correct fix) would be helpful for Shock users new to docker.
