### ISSUE TITLE
Shock API to Download File Saves as Node ID Instead of Filename

### ISSUE THREAD

**Issue by pfrybar** [MG-RAST/Shock#39]
When you download a file using the Node API it should save the file with the original filename and extension. Right now it saves using the Node ID which is uninformative.

e.g. http://kbase.us/services/shock-api/node/d446054f-ce0d-4ac2-b63f-79bd40071c20?download
saves to 'd446054f-ce0d-4ac2-b63f-79bd40071c20' instead of '47.fna.gz'

You can use the Content-Disposition header to specify the filename: http://stackoverflow.com/questions/1628260/downloading-a-file-with-a-different-name-with-php

**Comment by wltrimbl** [comment]
Content-disposition headers were implemented in 2017, ae2cfd02e1ddafc10fb5125e989b79dd21b4a714
